### PR TITLE
Support Ag-Star and ublox NEO-M8N

### PR DESCRIPTION
**Pull request by kibergus**
Hello. Thank you for the library. I've tried to use it with NMEA output of NovaTel Ag-Star and ublox NEO-M8N recievers and there vere some issues:

Ag-Star sends only GGA, VTG, GSV and GSA messages. So PositionProvider needs to use VTG instead of RMC.

NEO-M8N sends a lot of different messages. But when there is no movement RMC does not contain course attribute. So I've allowed PositionEvent to have null course if the course is not known.

### CODE REVIEW

**Comment by kibergus** [comment]
I've encountered one more problem. NovaTel Ag-Star outputs data at 10Hz rate. That means 10 GGA messages, 10 VTG and several messages about satellites every second. marine-api can't parse data that fast. So I've removed interval. Data is read when it is ready. When source stream ends, then parsing stops.

**Comment by ktuukkan** [comment]
Hi, thanks for the provider additions, looking good. But I'm not sure if I understand why to remove setInterval() totally as you can simply set it zero as needed. This setter was just added for exactly this purpose, so I would not like to deprecate it immediately. Also, it may well be good have data processed at even slower pace than default interval, e.g. for replaying logs.

**Comment by kibergus** [comment]
> Can you split your commits in different PRs?

Sorry, I've made pull request from my master branch and forgot that github will add all further commits to the pull request. I'll make separate pull requests later.

> But I'm not sure if I understand why to remove setInterval() totally as you can simply set it zero as needed. 

DefaultDataReader:27
```
		if(input.ready()) {
			data = input.readLine();
		}
```
This will become busy loop if timeout is set to zero. I think, there also will be busy loop of input stream ends. I don't see a need for that interval because both readLine in DefaultDataReader and socket.receive in UDPDataReader are blocking. They will wait until data is available.

> Also, it may well be good to have data processed at even slower pace than default interval, e.g. for replaying logs.

This is not quite reliable because message rate is not constant. So you can't play NMEA logs with predefined speed at that level. You need to look in-to timestamps inside messages and make pauses there.

**Comment by kibergus** [comment]
I'll close this pull request and make two separate requests instead of it.

**Pull request closed without merging**
