### PR TITLE
Add OSGi MANIFEST headers

### PR DESCRIPTION
**Pull request by balazs-zsoldos**
If you could, please, add the OSGi MANIFEST headers in the next release, that would be great.

### CODE REVIEW

**Comment by ktuukkan** [comment]
Hi, thanks for your PR. I'm not too familiar with OSGi, so alllow me to confirm this will not affect snapshotting and releasing in Maven Central?

**Comment by balazs-zsoldos** [comment]
Hi @ktuukkan,

I already uploaded the last stable version to maven-central with the OSGi manifest headers with: org.everit.osgi.bundles:org.everit.osgi.bundles.net.sf.marineapi coordinates. I do not intent to upload it every time if the original project contains the required headers, too.

The modification I sent does nothing else but adds some lines to MANIFEST.MF file. After that, I released to maven-central with standard commands, I guess your method should work, too.

If you need help with OSGi, please let me know.

**Comment by ktuukkan** [comment]
@balazs-zsoldos, I released a new version some days ago but the standard procedure, `release:prepare` followed by `release:perform`, doesn't seem to do anything for the additional coordinates. Any ideas?

**Comment by balazs-zsoldos** [comment]
@ktuukkan I am not sure what you mean. I do releases manually always with a very long shell command and I do not use the release plugin of maven.

The MANIFEST.MF file of version 0.10.0 on maven central contains the necessary OSGi MANIFEST headers. It should run perfectly in a modularized environment now. Do you miss something during running the _release_ goals of maven? If yes, maven-bundle-plugin can be configured in the way that the packaging of the project is still JAR. In that case, the maven-jar-plugin has to have some config in the pom, too.

**Comment by ktuukkan** [comment]
I mean, the v0.10.0 artifacts have not been pushed in Maven Central along with the normal release.

Can you give an example of the shell command to use?

**Comment by balazs-zsoldos** [comment]
org.everit.osgi.bundles is just a temporary solution. Now that the _net.sf.marineapi:marineapi:0.10.0_ artifact also contains the MANIFEST headers, I will not upload anything to the org.everit.osgi.bundles groupId. This was the same with org.json. For years it did not contain the necessary headers so I uploaded it under org.everit.osgi.bundles groupId, but as soon as they made the changes, I discontinued to upload it under my groupId.

The command I use became quite complex in the last years :-) :

    mvn clean source:jar javadoc:jar install gpg:sign org.sonatype.plugins:nexus-staging-maven-plugin:deploy -DnexusUrl=https://oss.sonatype.org/ -DautoReleaseAfterClose=true -DserverId=ossrh -Dadditionalparam="-Xdoclint:none --allow-script-in-comments"

**Comment by ktuukkan** [comment]
Ok then we're all good. It kinda felt redundant in the first place and this explains it, thanks! :)

**Pull request merged**
